#tämän tiedoston avulla saadaan tietokanta, bäkkäri ja frontti kerralla käyntiin. Tietokanta omassa kontissa, bäkkäri ja front toisessa kontissa
version: '3'
services:
    backend:
      build: .
      ports:
        - "8000:8000"
    graphbookdb:
      build: "./docker_mysql"
      ports: 
        - "3306:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
        - graphbookdb
      environment: 
        PMA_HOST: graphbookdb
        PMA_PORT: 3306
        PMA_ARBITARY: 1
      restart: 
        always
      ports: 
        - "8080:80"
  